name: oldfashioned
version: git
summary: Ubuntu-Old-Fashioned
description: |
  This snap is meant to let you build ubuntu cloud images locally from a
  livecd-rootfs checkout.

grade: stable
confinement: classic
architectures: [ all ]

apps:
  oldfashioned:
    command: old-fashioned-image-build

parts:
  oldfashioned:
    plugin: nil
    source: .
    source-type: git
    override-build: |
      snapcraftctl build
      cp ../../../old-fashioned-image-build ../../../prime
      sudo add-apt-repository -y ppa:launchpad/ppa
      sudo apt-get update
      sudo apt-get install -y launchpad-buildd bzr python-ubuntutools
