name: oldfashioned
version: git
summary: Ubuntu-Old-Fashioned
description: |
  This snap is meant to let you build ubuntu cloud images locally from a
  livecd-rootfs checkout.

grade: stable
confinement: devmode
architectures: [ all ]

apps:
  oldfashioned:
    command: sudo -E old-fashioned-image-build

parts:
  oldfashioned:
    plugin: nil
    source: .
    source-type: git
    install: |
      sudo add-apt-repository -y ppa:launchpad/ppa
      sudo apt-get update
      sudo apt-get install -y launchpad-buildd bzr python-ubuntutools
