name: old-fashioned-image-build
version: git
summary: Ubuntu Old Fashioned Image Builder
description: |
  This snap is meant to let you build ubuntu cloud images locally from a
  livecd-rootfs checkout.

grade: stable
confinement: classic
architectures: [ all ]

apps:
  old-fashioned-image-build:
    command: old-fashioned-image-build

parts:
  oldfashioned:
    plugin: nil
    source: .
    source-type: git
    build-packages:
      - bzr
    override-build: |
      snapcraftctl build

      cp ../../../old-fashioned-image-build ../../../prime

      sudo add-apt-repository -y ppa:launchpad/ppa
      sudo apt-get update
      sudo apt-get install -y launchpad-buildd python-ubuntutools
